### ISSUE TITLE
StephanoI_WaitForConfirm misses replies sometimes

### ISSUE THREAD

**Issue by alexbrickwedde** [WurthElektronik/WirelessConnectivity-SDK_STM32#13]
Hi,

i'm having issues calling StephanoI_ATBluetoothLE_PeripheralNotifyClient:
Sometimes waiting for the ">" or "OK" confirm times out, although the reply came in. 

I have a log from my microcontroller and a screenshot from my logic analyzer, which look plausible.
">>" lines are sent to the Stephano-I and logged from the top of UartTransmitInternal.
"<<" lines are received from the Stephano-I and logged from the top of StephanoI_HandleRxLine
"Timeout!" is the last line before returning false from StephanoI_WaitForConfirm_ex

Most times the PinReset "ready" reply is not detected also and times out.

Anyone else experiencing similar issues? I'm still at 2.0.0, do i need to update?

Best regards

...Alex

[BLEGATTSNTFY-6.txt](https://github.com/user-attachments/files/16350384/BLEGATTSNTFY-6.txt)

![BLEGATTSNTFY-6-0](https://github.com/user-attachments/assets/34fa8737-4c92-425d-b5f3-261ce2d26920)

![BLEGATTSNTFY-6-1](https://github.com/user-attachments/assets/0bb3a31b-d708-499d-a110-2b38c215b9d5)

```
00.019 OK    : PinReset
00.560 <<    : ready
05.020 NOK   : Startup event
05.021 >>    : ATE0

```

**Comment by alexbrickwedde** [comment]
Found it. My logging output, together with many CAN bus interrupts cause the `StephanoI_WaitForConfirm_ex `to be called, after the "OK" or ">" reply already arrived. At the top of that function, the `StephanoI_cmdConfirmStatus` is set to `StephanoI_CNFStatus_Invalid` - overwriting the already arrived status. I removed the reset of `StephanoI_cmdConfirmStatus` from that function and placed it in front of all those commands needing a StephanoI_WaitForConfirm.

**Comment by alexbrickwedde** [comment]
And the "NOK Startup Event" is caused by a 0 character sent by the Stephano-I after reset line (D6 in the screenshot) is set to high. So `\0\0ready` didn't match the expected `ready`. Since we are ASCII only, I'll skip 0 characters from being sent to the UART handler.

Just for safety i removed `StephanoI_Examples_startupEventReceived = false;` from `StephanoI_Examples_WaitForStartup` and placed it before the reset/restore code.

![nokpinreset](https://github.com/user-attachments/assets/41b6c44b-b0c2-489e-867e-7a03d21ccf0c)

**Comment by mah-eiSmart** [comment]
> And the "NOK Startup Event" is caused by a 0 character sent by the Stephano-I after reset line (D6 in the screenshot) is set to high. So `\0\0ready` didn't match the expected `ready`. Since we are ASCII only, I'll skip 0 characters from being sent to the UART handler.
> 
> Just for safety i removed `StephanoI_Examples_startupEventReceived = false;` from `StephanoI_Examples_WaitForStartup` and placed it before the reset/restore code.
> 
> ![nokpinreset](https://private-user-images.githubusercontent.com/396286/351437102-41b6c44b-b0c2-489e-867e-7a03d21ccf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTc2MDEsIm5iZiI6MTcyMTc5NzMwMSwicGF0aCI6Ii8zOTYyODYvMzUxNDM3MTAyLTQxYjZjNDRiLWIwYzItNDg5ZS04NjdlLTdhMDNkMjFjY2YwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNTAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTI4ZmFmMDU0ODBkYTk2ZTdiMGM3NGI2ZmEyZGVjNDE2ZmQzZDc3MjFjNDA2ZDZmMzEyMzA3ODI1NDU4ZTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dQtwWHzGiFreCV84xXAB7M6EK_Yx160Uplkg4ZYvRlQ)

@alexbrickwedde, what controller are you using? In our tests we did not see that behaviour. The "ready" message has been received clean, in any scenario.

**Comment by mah-eiSmart** [comment]
> And the "NOK Startup Event" is caused by a 0 character sent by the Stephano-I after reset line (D6 in the screenshot) is set to high. So `\0\0ready` didn't match the expected `ready`. Since we are ASCII only, I'll skip 0 characters from being sent to the UART handler.
> 
> Just for safety i removed `StephanoI_Examples_startupEventReceived = false;` from `StephanoI_Examples_WaitForStartup` and placed it before the reset/restore code.
> 
> ![nokpinreset](https://private-user-images.githubusercontent.com/396286/351437102-41b6c44b-b0c2-489e-867e-7a03d21ccf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTc2MDEsIm5iZiI6MTcyMTc5NzMwMSwicGF0aCI6Ii8zOTYyODYvMzUxNDM3MTAyLTQxYjZjNDRiLWIwYzItNDg5ZS04NjdlLTdhMDNkMjFjY2YwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNTAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTI4ZmFmMDU0ODBkYTk2ZTdiMGM3NGI2ZmEyZGVjNDE2ZmQzZDc3MjFjNDA2ZDZmMzEyMzA3ODI1NDU4ZTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dQtwWHzGiFreCV84xXAB7M6EK_Yx160Uplkg4ZYvRlQ)

@alexbrickwedde, thank you for providing this info. The reported behaviour is a timing issue, as you correctly figured out. The `StephanoI_WaitForConfirm_ex` function is called immediatly after the UART request `AT+BLEGATTSNTFY` has been sent from the host to the module. Thus it's hard to miss the first response `>`. However, since you miss it in your test setup, you found already a proper solution to overcome that.

**Comment by alexbrickwedde** [comment]
> @alexbrickwedde, what controller are you using? In our tests we did not see that behaviour. The "ready" message has been received clean, in any scenario.

It's a STM32H735.

It looks like the TX Pin of the Stephano-I is pulled low after reset for 350µs, my UART reads a 0 then.
