### ISSUE TITLE
EVENTENTRY("busy p…", StephanoI_ATEvent_Busy) contains unicode U+2026 instead of three dots

### ISSUE THREAD

**Issue by alexbrickwedde** [WurthElektronik/WirelessConnectivity-SDK_STM32#14]
I don't know, if the code is needed or if it's an issue.

The source code `EVENTENTRY("busy p…", StephanoI_ATEvent_Busy)` contains unicode U+2026 instead of three dots. While `(0 == strcmp(rxPacket, "busy p..."))` contains three dots.

**Comment by mah-eiSmart** [comment]
@alexbrickwedde, thank you for reporting this issue. It will be fixed in the next release.
