### ISSUE TITLE
Timeout for ATE needs to be 100s?

### ISSUE THREAD

**Issue by alexbrickwedde** [WurthElektronik/WirelessConnectivity-SDK_STM32#15]
Hi,

https://github.com/WurthElektronik/WirelessConnectivity-SDK_STM32/blob/v2.1.0/WCON_SDK/WCON_Drivers/StephanoI/ATCommands/ATDevice.c#L338

It'll wait for 100s - is that really needed for ATE?

(I'm using the UART at high speed and check if the module replies, if not i'll switch to 115200 and reconfigure the module to high speed - takes 100s now)

Best Regards

...Alex

**Comment by mah-eiSmart** [comment]
hi @alexbrickwedde,

the ATE command returns OK immediately (after less than 50 ms). Thus the function `StephanoI_ATDevice_EchoOn` should not run into the timeout as it receives the OK within 50 ms.
The 100s timeout is much too high, even for the other commands using that timeout value. We will correct that.

Thank you for the feedback.
BR Matthias
