### ISSUE TITLE
[Feature Request] Proteus-III SPI version

### ISSUE THREAD

**Issue by Stefasaur** [WurthElektronik/WirelessConnectivity-SDK_STM32#16]
Currently, we are looking at the SPI implementation of the Proteus-III. However, as I understand, this is only implemented via the linux drivers [in this repo](https://github.com/WurthElektronik/WirelessConnectivity-SDK/tree/master). Are there any plans to also include SPI communication methods for microcontrollers for the Proteus-III SPI or should we do this for ourselves? @mah-eiSmart

**Comment by mah-eiSmart** [comment]
@Stefasaur, in nearby future, there won't be drivers supporting the product Proteus-III-SPI on STM32.
Are you working on STM32?
If not, you can anyways take the driver files of Proteus-III and replace UART by SPI. But I guess, that's not new to you.

BTW: The specification of the Proteus-III-SPI's SPI interface is available in it's user manual [https://www.we-online.de/katalog/de/manual/2611011024010](url) chapter 6.1.

**Comment by Stefasaur** [comment]
@mah-eiSmart Thanks for your response. I need to implement this on an ESP32, although it doesn`t really matter which uC it is. I have seen the STM32 UART implementation, but I do not know if it is better to change this to SPI, or to port the linux repo for the SPI version to my uC. It is hard to tell what is better, since this would require a lot of knowledge on the protocol differences between the SPI and UART implementation.

**Comment by mah-eiSmart** [comment]
@Stefasaur the interface to choose, depends on you. If you need the highest throughput, you need the SPI-version (the linux driver is a good base, I checked that), otherwise take the UART one. The UART-version of the module is easier in terms of usage. In general I recommend that.

BTW: We have the [Orthosie-I](https://www.we-online.com/de/components/products/ORTHOSIE-I) module, which uses ESP32C3 chipset with Wifi AND Bluetooth LE connectivity. Maybe you can port your ESP32-firmware to that chip, and have both wireless interfaces integrated without additional hardware.

**Comment by Stefasaur** [comment]
@mah-eiSmart Thank you for your quick feedback, If i have other questions I will ask later here, or you can give me your contact.

**Comment by Stefasaur** [comment]
One last question for now @mah-eiSmart. As I see, the Proteus-III does not support operation in Central mode via the host-slave comms, is this true?

**Comment by mah-eiSmart** [comment]
@Stefasaur Proteus-III supports central mode as well. what do you mean by "host-slave comms" ?

**Comment by Stefasaur** [comment]
@mah-eiSmart O.K., thank you. I meant via the SPI/UART communication protocol.

**Comment by mah-eiSmart** [comment]
@Stefasaur yes, of course. Central functions are available via UART/SPI. Please use support.86@we-online.de for contact.

**Comment by Stefasaur** [comment]
I will close this 'issue", since the main topic has been answered.
