### ISSUE TITLE
WE_Pin_t contains a STM pin definition

### ISSUE THREAD

**Issue by oedze** [WurthElektronik/WirelessConnectivity-SDK_STM32#2]
The file `WCON_SDK/WCON_Drivers/global/global_types.h` contains the `WE_Pin_t` struct which contains a the `GPIO_TypDef` type. This is a STM specific type and it won't work on other platforms.
I need to use this library in combination with a esp32 and this won't compile right now.

**Comment by mah-eiSmart** [comment]
Thank you @oedze,this will be considered in one of the next updates.

**Comment by wm-eisos** [comment]
Hey

This has been fixed in the latest version v2.0.0 (7faf9c8aaaa09c94a8b786f1ca0002861eedea74)

Best Regards
Wajdi
