### ISSUE TITLE
Redundant code in Fillchecksum

### ISSUE THREAD

**Issue by timnMK** [WurthElektronik/WirelessConnectivity-SDK_STM32#3]
if ((cmd->Length >= 0) && (cmd->Stx == CMD_STX))

My PIC compiler moans that the first expression always produces a true result, quite right too. I've removed it and just left the Stx expression, all seems to work OK unless there is some hidden feature here?

**Comment by wm-eisos** [comment]
Hey,

Yes that is correct.
A new major release of the drivers has been released v2.0.0 (7faf9c8aaaa09c94a8b786f1ca0002861eedea74)

Best Regards
Wajdi
