### ISSUE TITLE
Support for DHCP option 114 (Captive Portal)

### ISSUE THREAD

**Issue by alexbrickwedde** [WurthElektronik/WirelessConnectivity-SDK_STM32#6]
Could you add support for DHCP option 114 (Captive Portal) as in RFC8910 when running an AP?

**Comment by mah-eiSmart** [comment]
We are checking if it's possible. When I understand correctly, this is not related to this driver/repository.

**Comment by alexbrickwedde** [comment]
> We are checking if it's possible. When I understand correctly, this is not related to this driver/repository.

This library should also support it, after it's added to the "AT Firmware" :-) (i haven't found it here, is it open source?)

**Comment by mah-eiSmart** [comment]
> > We are checking if it's possible. When I understand correctly, this is not related to this driver/repository.
> 
> This library should also support it, after it's added to the "AT Firmware" :-) (i haven't found it here, is it open source?)

Then I understood correctly. This feature will be considered for the next release, in case we have access to it. I will forward your request to the team dealing with that topic.
