### ISSUE TITLE
StephanoI_ATBluetoothLE_ParsePeripheralDiscoverCharacteristics doesn't parse correctly

### ISSUE THREAD

**Issue by alexbrickwedde** [WurthElektronik/WirelessConnectivity-SDK_STM32#7]
Regarding the function "StephanoI_ATBluetoothLE_ParsePeripheralDiscoverCharacteristics", the line `if (!ATCommand_GetNextArgumentString(&argumentsP, t->characteristics_type, ATCOMMAND_ARGUMENT_DELIM, sizeof(t->characteristics_type)))`:

sizeof(t->characteristics_type) is 5, but the content received from the Stephano-I is
`+BLEGATTSCHAR:"char",1,1,0x6E400002C35211E5953D0002A5D5C51B,0x0c` which means `"char"` is 6 characters long.

The quotation character is not parsed away and later `0 == strcmp(t->characteristics_type, "char")`, and probably desc too, won't match.

**Comment by alexbrickwedde** [comment]
And it's also missing code to read the UUID.

**Comment by mah-eiSmart** [comment]
> BluetoothLE_ParsePeripheralDiscoverCharacteris

Please use function ATCommand_GetNextArgumentStringWithoutQuotationMarks instead of ATCommand_GetNextArgumentString. We will fix this.

**Comment by mah-eiSmart** [comment]
> And it's also missing code to read the UUID.

Right, will de added.

**Comment by mah-eiSmart** [comment]
Will be fixed in the next release.
