### ISSUE TITLE
Missing "desc" in +WRITE message

### ISSUE THREAD

**Issue by alexbrickwedde** [WurthElektronik/WirelessConnectivity-SDK_STM32#8]
I got a +WRITE message with `0,1,1,,4,rrrr`, which should be valid, according to the UM:
![image](https://github.com/WurthElektronik/WirelessConnectivity-SDK_STM32/assets/396286/7b7c176a-8552-4944-b68e-a39c1c333a44)

In function StephanoI_ATBluetoothLE_ParseWrite the `ATCommand_GetNextArgumentInt(&argumentsP, &(t->desc), ...` doesn't find content and returns false.

**Comment by alexbrickwedde** [comment]
```
  if (argumentsP[0] == ',') {
    t->desc = 0;
    argumentsP++;
  } else {
    if (!ATCommand_GetNextArgumentInt(&argumentsP, &(t->desc), ATCOMMAND_INTFLAGS_SIZE8 | ATCOMMAND_INTFLAGS_UNSIGNED, ATCOMMAND_ARGUMENT_DELIM))
    {
      return false;
    }
  }
```
works for me

**Comment by mah-eiSmart** [comment]
Thank you for the feedback. This fix is correct, it will be part of the next release.
